# Generated by Django 3.2.7 on 2022-09-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='program',
            field=models.CharField(blank=True, choices=[('BSc', 'BSc'), ('BA', 'BA'), ('MS', 'MS'), ('MBA', 'MBA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Registrar', 'Registrar'), ('Guest', 'Guest')], default=[('', '---------')], max_length=15),
        ),
    ]
