# Generated by Django 3.2.7 on 2021-10-05 13:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211003_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=users.models.path_and_rename, verbose_name='Profile Pictures'),
        ),
    ]
