# Generated by Django 4.1.1 on 2022-09-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=23)),
                ('programDescription', models.CharField(max_length=63)),
                ('programInfoLink', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=127)),
                ('departmentDescription', models.CharField(max_length=1023)),
                ('program', models.ManyToManyField(to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=255)),
                ('courseDescription', models.CharField(max_length=1023)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.department')),
            ],
        ),
    ]
