# Generated by Django 4.1.1 on 2022-09-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='departmentHead',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
