# Generated by Django 4.1.1 on 2022-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_department_departmenthead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='programId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
