# Generated by Django 4.1.1 on 2022-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_courses_courseid_alter_department_departmentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseDescription',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentDescription',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='programDescription',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='programInfoLink',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
