# Generated by Django 4.1.1 on 2022-09-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_courses_coursedescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='programName',
            field=models.CharField(max_length=63),
        ),
    ]
