# Generated by Django 4.1.1 on 2022-09-26 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_program_programname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batchId', models.AutoField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(max_length=63)),
                ('batchEntryYear', models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)])),
                ('batchGraduationYear', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='department',
            name='program',
        ),
        migrations.CreateModel(
            name='Courses_in_Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchEntryYear', models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)])),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.batches')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program'),
        ),
    ]
