# Generated by Django 4.1.1 on 2022-09-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_batches_remove_courses_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses_in_batch',
            name='batchEntryYear',
        ),
        migrations.AddField(
            model_name='courses',
            name='resources',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='resources',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
