# Generated by Django 4.1.1 on 2022-09-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_remove_courses_in_batch_batchentryyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='programInfoLink',
        ),
    ]
