# Generated by Django 4.1.1 on 2022-09-20 08:23

from django.db import migrations, models
import django.db.models.deletion
import school_users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchId', models.PositiveSmallIntegerField()),
                ('batchName', models.CharField(max_length=63)),
                ('batchEntryYear', models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)])),
                ('batchGraduationYear', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registrars',
            fields=[
                ('registrarId', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32)),
                ('birthdate', models.DateField(null=True)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('EducationLevel', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentId', models.CharField(max_length=63, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32)),
                ('birthdate', models.DateField(null=True)),
                ('citizenship', models.CharField(max_length=127, null=True)),
                ('country', models.CharField(max_length=127, null=True)),
                ('city', models.CharField(max_length=63, null=True)),
                ('documentLocation', models.CharField(max_length=511)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('EducationLevel', models.CharField(max_length=255)),
                ('academicYear', models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('currentSemester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('enrollment_type', models.CharField(choices=[('Regular', 'Regular'), ('Online', 'Online')], default='Regular', max_length=23)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_users.batches')),
                ('courses', models.ManyToManyField(to='programs.courses')),
                ('department', models.ManyToManyField(to='programs.department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('lectureId', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32)),
                ('birthdate', models.DateField(null=True)),
                ('citizenship', models.CharField(max_length=127, null=True)),
                ('country', models.CharField(max_length=127, null=True)),
                ('city', models.CharField(max_length=63, null=True)),
                ('documentLocation', models.CharField(max_length=511)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('EducationLevel', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='programs.courses')),
                ('department', models.ManyToManyField(to='programs.department')),
                ('program', models.ManyToManyField(to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('guestId', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32)),
                ('birthdate', models.DateField(null=True)),
                ('citizenship', models.CharField(max_length=127, null=True)),
                ('country', models.CharField(max_length=127, null=True)),
                ('city', models.CharField(max_length=63, null=True)),
                ('documentLocation', models.CharField(max_length=511)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('EducationLevel', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='programs.courses')),
            ],
        ),
    ]
