# Generated by Django 4.1.1 on 2022-09-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_program_programinfolink_program_resourceaddress'),
        ('school_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='EducationLevel',
        ),
        migrations.AlterField(
            model_name='guests',
            name='citizenship',
            field=models.CharField(default='Ethiopian', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='city',
            field=models.CharField(default='Addis Ababa', max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='country',
            field=models.CharField(default='Ethiopia', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='documentLocation',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='email',
            field=models.EmailField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='guestId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guests',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='documentLocation',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='email',
            field=models.EmailField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='lectureId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='registrars',
            name='EducationLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program'),
        ),
        migrations.AlterField(
            model_name='registrars',
            name='email',
            field=models.EmailField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='registrars',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='registrars',
            name='registrarId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.batches'),
        ),
        migrations.AlterField(
            model_name='students',
            name='documentLocation',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='studentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Batches',
        ),
    ]
