# Generated by Django 4.1.1 on 2022-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='id',
        ),
        migrations.AlterField(
            model_name='batches',
            name='batchId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
