# Generated by Django 4.1.1 on 2022-09-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0002_remove_students_educationlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='previousEducationLevel',
            field=models.CharField(choices=[], default='Bachelor', max_length=127),
        ),
    ]
