# Generated by Django 4.1.1 on 2022-09-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_courses_coursedescription_and_more'),
        ('school_users', '0002_remove_batches_id_alter_batches_batchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='EducationLevel',
        ),
        migrations.AddField(
            model_name='students',
            name='previousEducationLevel',
            field=models.CharField(choices=[('Bachelor of Science', 'Bachelor of Science')], default='Bachelor', max_length=127),
        ),
        migrations.AlterField(
            model_name='guests',
            name='documentLocation',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='email',
            field=models.EmailField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='documentLocation',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='email',
            field=models.EmailField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='registrars',
            name='EducationLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program'),
        ),
        migrations.AlterField(
            model_name='registrars',
            name='email',
            field=models.EmailField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='registrars',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='documentLocation',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phoneNumber',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
