# Generated by Django 4.1.1 on 2022-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0003_students_previouseducationlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturers',
            name='EducationLevel',
        ),
        migrations.AddField(
            model_name='lecturers',
            name='educationLevel',
            field=models.CharField(choices=[], default='Bachelor', max_length=127),
        ),
    ]
