# Generated by Django 4.1.1 on 2022-09-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0003_remove_students_educationlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='guestId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='lectureId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrars',
            name='registrarId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='previousEducationLevel',
            field=models.CharField(choices=[('Bachelor of Science', 'Bachelor of Science'), ('High School', 'High School'), ('Master of Science', 'Master of Science'), ('Primary', 'Primary'), ('MBA', 'MBA'), ('MEng', 'MEng')], default='Bachelor', max_length=127),
        ),
        migrations.AlterField(
            model_name='students',
            name='studentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
