# Generated by Django 4.1.1 on 2022-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0004_remove_lecturers_educationlevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='EducationLevel',
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='educationLevel',
            field=models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng')], default='Bachelor', max_length=127),
        ),
        migrations.AlterField(
            model_name='students',
            name='previousEducationLevel',
            field=models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng')], default='Bachelor', max_length=127),
        ),
        migrations.AddField(
            model_name='guests',
            name='educationLevel',
            field=models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng')], default='Bachelor', max_length=127),
        ),
    ]
