# Generated by Django 4.1.1 on 2022-09-26 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_batches_remove_courses_semester_and_more'),
        ('school_users', '0004_alter_guests_guestid_alter_lecturers_lectureid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='citizenship',
            field=models.CharField(default='Ethiopian', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='city',
            field=models.CharField(default='Addis Ababa', max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='country',
            field=models.CharField(default='Ethiopia', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.batches'),
        ),
        migrations.DeleteModel(
            name='Batches',
        ),
    ]
