# Generated by Django 4.1.1 on 2022-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0005_remove_guests_educationlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='previousEducationLevel',
            field=models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng')], max_length=127),
        ),
    ]
