# Generated by Django 4.1.1 on 2022-09-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0006_alter_students_previouseducationlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests',
            old_name='courses',
            new_name='shortCourses',
        ),
        migrations.AddField(
            model_name='guests',
            name='educationDepartment',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration')], default='MS', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturers',
            name='educationDepartment',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration')], default='MS', max_length=127),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
