# Generated by Django 4.1.1 on 2022-09-29 19:40

from django.db import migrations, models
import django.db.models.deletion
import school_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_program_programinfolink_program_resourceaddress'),
        ('school_users', '0007_rename_courses_guests_shortcourses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63, null=True)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('citizenship', models.CharField(max_length=127, null=True)),
                ('country', models.CharField(max_length=127, null=True)),
                ('city', models.CharField(max_length=63, null=True)),
                ('documentLocation', models.CharField(max_length=511, null=True)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('previousEducationLevel', models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng')], max_length=127)),
                ('previousEducationDepartment', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration')], max_length=127)),
                ('academicYear', models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('currentSemester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('enrollment_type', models.CharField(choices=[('Regular', 'Regular'), ('Online', 'Online')], default='Regular', max_length=23)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.batches')),
                ('courses', models.ManyToManyField(to='programs.courses')),
                ('department', models.ManyToManyField(to='programs.department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
            ],
        ),
    ]
