# Generated by Django 4.1.1 on 2022-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0008_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guests',
            options={'ordering': ['firstName']},
        ),
        migrations.AlterModelOptions(
            name='lecturers',
            options={'ordering': ['firstName']},
        ),
        migrations.AlterModelOptions(
            name='registrars',
            options={'ordering': ['firstName']},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['firstName']},
        ),
        migrations.AlterField(
            model_name='guests',
            name='email',
            field=models.EmailField(default='email@as.com', max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='email',
            field=models.EmailField(default='email@as.com', max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrars',
            name='email',
            field=models.EmailField(default='email@as.com', max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='email@as.com', max_length=63, unique=True),
            preserve_default=False,
        ),
    ]
