# Generated by Django 4.1.1 on 2022-10-01 10:51

from django.db import migrations, models
import django.db.models.deletion
import school_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_program_programinfolink_program_resourceaddress'),
        ('school_users', '0010_remove_registrars_educationlevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guestId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('citizenship', models.CharField(default='Ethiopian', max_length=127, null=True)),
                ('country', models.CharField(default='Ethiopia', max_length=127, null=True)),
                ('city', models.CharField(default='Addis Ababa', max_length=63, null=True)),
                ('documentLocation', models.CharField(max_length=511, null=True)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('educationLevel', models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng'), ('BS', 'BS')], default='Bachelor', max_length=127)),
                ('educationDepartment', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration'), ('Information Technology', 'Information Technology')], max_length=127)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('shortCourses', models.ManyToManyField(to='programs.courses')),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lectureId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('citizenship', models.CharField(max_length=127, null=True)),
                ('country', models.CharField(max_length=127, null=True)),
                ('city', models.CharField(max_length=63, null=True)),
                ('documentLocation', models.CharField(max_length=511, null=True)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('educationLevel', models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng'), ('BS', 'BS')], default='Bachelor', max_length=127)),
                ('educationDepartment', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration'), ('Information Technology', 'Information Technology')], max_length=127)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='programs.courses')),
                ('department', models.ManyToManyField(to='programs.department')),
                ('program', models.ManyToManyField(to='programs.program')),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('registrarId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('educationLevel', models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng'), ('BS', 'BS')], default='Bachelor', max_length=127)),
                ('educationDepartment', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration'), ('Information Technology', 'Information Technology')], max_length=127)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=63)),
                ('middleName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=63, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=32, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('citizenship', models.CharField(max_length=127, null=True)),
                ('country', models.CharField(max_length=127, null=True)),
                ('city', models.CharField(max_length=63, null=True)),
                ('documentLocation', models.CharField(max_length=511, null=True)),
                ('profilePicDir', models.ImageField(blank=True, upload_to=school_users.models.path_and_rename, verbose_name='Profile Pictures')),
                ('previousEducationLevel', models.CharField(choices=[('MA', 'MA'), ('MS', 'MS'), ('BSc', 'BSc'), ('BA', 'BA'), ('BEng', 'BEng'), ('BS', 'BS')], max_length=127)),
                ('previousEducationDepartment', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration'), ('Information Technology', 'Information Technology')], max_length=127)),
                ('academicYear', models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('currentSemester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('enrollment_type', models.CharField(choices=[('Regular', 'Regular'), ('Online', 'Online')], default='Regular', max_length=23)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.batches')),
                ('courses', models.ManyToManyField(to='programs.courses')),
                ('department', models.ManyToManyField(to='programs.department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.RemoveField(
            model_name='guests',
            name='shortCourses',
        ),
        migrations.RemoveField(
            model_name='lecturers',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='lecturers',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lecturers',
            name='program',
        ),
        migrations.DeleteModel(
            name='Registrars',
        ),
        migrations.RemoveField(
            model_name='students',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
        migrations.RemoveField(
            model_name='students',
            name='program',
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
        migrations.DeleteModel(
            name='Lecturers',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
